'use client'
import { useState, useEffect } from 'react'
type Curso = { id:string, nome:string, desc:string, thumb:string, video:string, progresso:number }
export default function Admin(){
  const [logado,setLogado]=useState(false); const [cursos,setCursos]=useState<Curso[]>([]);
  useEffect(()=>{ const c=localStorage.getItem('hope_cursos'); if(c) setCursos(JSON.parse(c)) },[]);
  const salvar=(novos:Curso[])=>{ setCursos(novos); localStorage.setItem('hope_cursos', JSON.stringify(novos)) };
  if(!logado) return (<div className="min-h-screen bg-black flex items-center justify-center"><div className="bg-[#121212] border border-[#222] p-6 rounded-xl w-[320px]"><h1 className="font-black text-white">ADMIN HOPE<span className="text-[#FF6B00]">+</span></h1><input id="u" defaultValue="admin" className="w-full mt-4 p-3 bg-[#1C1C1C] rounded-xl text-white"/><input id="p" defaultValue="admin123" type="password" className="w-full mt-2 p-3 bg-[#1C1C1C] rounded-xl text-white"/><button onClick={()=>{ const u=(document.getElementById('u') as HTMLInputElement).value; const p=(document.getElementById('p') as HTMLInputElement).value; if(u==='admin'&&p==='admin123') setLogado(true)}} className="w-full mt-3 p-3 bg-[#FF6B00] rounded-xl text-white font-bold">ENTRAR</button></div></div>);
  return (<div className="min-h-screen bg-[#050507] text-white p-6"><div className="flex justify-between max-w-[1100px]"><h1 className="text-xl font-bold">Painel Admin - Conectado</h1><a href="/" className="text-[#FF6B00]">→ Aluno</a></div><div className="grid grid-cols-3 gap-4 mt-6 max-w-[1100px]">{cursos.map(c=>(<div key={c.id} className="bg-[#121212] border border-[#1E1E1E] rounded-xl p-4"><img src={c.thumb} className="w-full h-[90px] object-cover rounded-lg"/><b className="block mt-3 text-sm">{c.nome}</b><div className="mt-3 flex flex-col gap-2"><input value={c.video} onChange={e=>{ const novos=cursos.map(x=>x.id===c.id?{...x, video:e.target.value}:x); salvar(novos)}} className="w-full p-2 bg-[#0C0C0C] border border-[#222] rounded-lg text-[11px] text-white"/><input value={c.nome} onChange={e=>{ const novos=cursos.map(x=>x.id===c.id?{...x, nome:e.target.value}:x); salvar(novos)}} className="w-full p-2 bg-[#0C0C0C] border border-[#222] rounded-lg text-xs text-white"/><div className="flex items-center gap-2"><input type="range" min={0} max={100} value={c.progresso} onChange={e=>{ const novos=cursos.map(x=>x.id===c.id?{...x, progresso:Number(e.target.value)}:x); salvar(novos)}} className="flex-1 accent-[#FF6B00]"/><span className="text-[10px] text-[#FF6B00]">{c.progresso}%</span></div></div></div>))}</div></div>);
}