'use client'
import { useState, useEffect } from 'react'
type Curso = { id:string, nome:string, desc:string, thumb:string, video:string, progresso:number }
const CURSOS_PADRAO:Curso[] = [
  {id:'codigo', nome:'Código da Disciplina', desc:'6/8 aulas', thumb:'/codigo.svg', video:'https://www.youtube.com/embed/dQw4w9WgXcQ', progresso:75},
  {id:'sabotadores', nome:'7 Sabotadores', desc:'3/6 aulas', thumb:'/sabotadores.svg', video:'https://www.youtube.com/embed/dQw4w9WgXcQ', progresso:50},
  {id:'personal', nome:'Personal Empresário', desc:'Concluído', thumb:'/personal.svg', video:'https://www.youtube.com/embed/dQw4w9WgXcQ', progresso:100},
  {id:'desafio70', nome:'Desafio 70 Dias', desc:'Dia 12/70', thumb:'/desafio70.svg', video:'https://www.youtube.com/embed/dQw4w9WgXcQ', progresso:30},
  {id:'pos', nome:'Pós-Graduação III', desc:'4/10 módulos', thumb:'/pos.svg', video:'https://www.youtube.com/embed/dQw4w9WgXcQ', progresso:40},
  {id:'mentoria', nome:'Mentoria', desc:'Hoje 19h', thumb:'/mentoria.svg', video:'https://www.youtube.com/embed/dQw4w9WgXcQ', progresso:20},
]
export default function Aluno(){
  const [logged,setLogged]=useState(false); const [nome,setNome]=useState('Lucas'); const [cursos,setCursos]=useState<Curso[]>(CURSOS_PADRAO); const [aberto,setAberto]=useState<Curso|null>(null); const [liberados,setLiberados]=useState<string[]>(['codigo','sabotadores','personal','desafio70','pos','mentoria']);
  useEffect(()=>{ const c=localStorage.getItem('hope_cursos'); if(c) setCursos(JSON.parse(c)); else localStorage.setItem('hope_cursos', JSON.stringify(CURSOS_PADRAO)); const a=localStorage.getItem('hope_aluno_atual'); if(a){ try{ const aluno=JSON.parse(a); setLiberados(aluno.cursosLiberados||liberados); setNome(aluno.nome); setLogged(true)}catch{} } },[]);
  const entrar=()=>{ const alunoAtual={nome, login:nome.toLowerCase()+'.hope', cursosLiberados:liberados, ultimoAcesso:new Date().toLocaleString()}; localStorage.setItem('hope_aluno_atual', JSON.stringify(alunoAtual)); let alunos=JSON.parse(localStorage.getItem('hope_alunos')||'[]'); if(!alunos.find((x:any)=>x.login===alunoAtual.login)){ alunos.push({id:Date.now().toString(),...alunoAtual, progresso:{}}); localStorage.setItem('hope_alunos', JSON.stringify(alunos)) } setLogged(true) };
  if(!logged) return (<div className="min-h-screen bg-[#050505] flex items-center justify-center p-4"><div className="w-[380px] bg-[#121212] border border-[#1E1E1E] rounded-[20px] p-7"><div className="text-[32px] font-black text-center text-white">HOPE<span className="text-[#FF6B00]">+</span></div><input value={nome} onChange={e=>setNome(e.target.value)} className="w-full mt-6 p-4 bg-[#1C1C1C] border border-[#333] rounded-xl text-white" placeholder="Seu nome"/><input type="password" defaultValue="123" className="w-full mt-3 p-4 bg-[#1C1C1C] border border-[#333] rounded-xl text-white"/><button onClick={entrar} className="w-full mt-4 p-4 bg-[#FF6B00] rounded-xl text-white font-extrabold">ENTRAR →</button></div></div>);
  return (<div className="min-h-screen bg-[#050507] text-white flex"><div className="w-[220px] bg-[#0C0C0C] border-r border-[#1A1A1A] p-3 flex flex-col"><div className="font-black px-2">🔥 HOPE<span className="text-[#FF6B00]">+</span></div><div className="mt-7 flex flex-col gap-1 text-[13px] text-[#5A5A5A]"><div className="bg-[#FF6B00] text-white px-3 py-2.5 rounded-xl">🔥 Início</div><div onClick={()=>{localStorage.removeItem('hope_aluno_atual'); setLogged(false)}} className="px-3 py-2.5 mt-6 cursor-pointer">🚪 Sair</div><a href="/admin" className="px-3 py-2.5 text-[#FF6B00]">⚙️ Admin</a></div></div><div className="flex-1 flex flex-col"><div className="h-[56px] bg-[#0C0C0C] border-b border-[#1A1A1A] flex justify-end items-center px-5 gap-2 text-[11px]"><div className="bg-[#141414] border border-[#222] rounded-full px-3 py-1.5">🔥 <b className="text-[#FF6B00]">12 dias</b></div><div className="bg-[#141414] border border-[#222] rounded-full px-3 py-1.5">👤 {nome}</div></div><div className="p-7"><h1 className="text-[22px] font-extrabold">Olá, {nome} — bem-vindo de volta! 🔥</h1><div className="grid grid-cols-3 gap-3 mt-6 max-w-[1020px]">{cursos.filter(c=>liberados.includes(c.id)).map(c=>(<div key={c.id} className="bg-[#121212] border border-[#1E1E1E] rounded-xl overflow-hidden hover:border-[#FF6B00] cursor-pointer" onClick={()=>setAberto(c)}><div className="h-[112px] bg-black"><img src={c.thumb} className="w-full h-full object-cover"/></div><div className="p-3"><b className="text-[12px]">{c.nome}</b><div className="flex items-center gap-2 mt-3"><div className="flex-1 h-[3px] bg-[#222] rounded"><div className="h-full bg-[#FF6B00]" style={{width:c.progresso+'%'}}></div></div><span className="text-[9px] bg-[#FF6B00] px-2 py-1 rounded-full font-bold">CONTINUAR</span></div></div></div>))}</div></div></div>{aberto && (<div className="fixed inset-0 bg-black/90 z-50 flex items-center justify-center p-4"><div className="w-full max-w-[800px] bg-[#121212] border border-[#222] rounded-2xl p-4"><div className="flex justify-between"><h2 className="font-bold">{aberto.nome}</h2><button onClick={()=>setAberto(null)} className="bg-[#222] px-3 py-1 rounded-full text-xs">✕ Voltar</button></div><div className="mt-4 aspect-video bg-black rounded-xl overflow-hidden"><iframe src={aberto.video} className="w-full h-full" allowFullScreen></iframe></div><button onClick={()=>setAberto(null)} className="w-full mt-4 p-3 bg-[#FF6B00] rounded-xl font-bold">← VOLTAR</button></div></div>)}</div>);
}