'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Play, CheckCircle2, Lock } from 'lucide-react'

type Course={id:string;tag:string;title:string;desc:string;thumb:string;progress:number;number:string;video?:string}
const defaults:Course[]=[
{id:'codigo',tag:'CÓDIGO',title:'Código da Disciplina',desc:'Sistema integrado de transformação humana aplicado à vida real.',thumb:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85',progress:75,number:'70'},
{id:'sabotadores',tag:'MENTALIDADE',title:'7 Sabotadores da Disciplina',desc:'Identifique os padrões que sabotam sua execução.',thumb:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=85',progress:50,number:'7'},
{id:'personal',tag:'NEGÓCIOS',title:'Personal Empresário',desc:'Transforme conhecimento, serviço e disciplina em negócio.',thumb:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85',progress:100,number:'12'},
{id:'desafio70',tag:'DESAFIO',title:'Desafio 70 Dias',desc:'Um ciclo de execução para construir consistência.',thumb:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=85',progress:30,number:'70'},
{id:'pos',tag:'ESTUDO',title:'Pós-Graduação III',desc:'Conteúdos de estudo, repertório e aplicação prática.',thumb:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=85',progress:40,number:'10'},
{id:'mentoria',tag:'AO VIVO',title:'Mentoria',desc:'Direcionamentos para transformar intenção em execução.',thumb:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85',progress:20,number:'19'}]

export default function Curso(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [course,setCourse]=useState<Course|null>(null); const [lesson,setLesson]=useState(0)
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('hope_content_v2')||'[]');const base=defaults.find(c=>c.id===id);const found=Array.isArray(saved)?saved.find((x:Course)=>x.id===id):null;setCourse({...base,...found})}catch{setCourse(defaults.find(c=>c.id===id)||defaults[0])}},[id])
 if(!course)return <div className="min-h-screen bg-[#0A0A0A]"/>
 const lessons=['Introdução','O princípio da disciplina','Aplicação na vida real','Exercício prático','Próximo nível']
 return <div className="min-h-screen bg-[#0A0A0A] text-white"><header className="h-16 border-b border-[#262626] bg-[#111] flex items-center px-4 md:px-8"><button onClick={()=>router.push('/aluno')} className="inline-flex items-center gap-2 text-sm text-[#aaa] hover:text-white"><ArrowLeft size={18}/>Voltar para conteúdos</button><div className="mx-auto text-xl font-extrabold text-[#FF6B00]">HOPE+</div><div className="w-32 hidden md:block"/></header><main className="max-w-7xl mx-auto p-4 md:p-8"><div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] gap-6"><section><div className="relative aspect-video rounded-2xl border border-[#262626] bg-[#151515] overflow-hidden flex items-center justify-center"><div className="absolute inset-0 opacity-25 bg-cover bg-center" style={{backgroundImage:`url(${course.thumb})`}}/><div className="relative h-16 w-16 rounded-full bg-[#FF6B00] grid place-items-center shadow-[0_0_40px_rgba(255,107,0,.25)]"><Play size={25} fill="white"/></div><span className="absolute bottom-4 left-4 text-xs text-white/60">Player HOPE+ · conteúdo protegido</span></div><div className="mt-6"><span className="inline-block rounded-md bg-[#FF6B00] px-2 py-1 text-[10px] font-bold">{course.tag}</span><h1 className="text-2xl md:text-3xl font-extrabold mt-3">{course.title}</h1><div className="mt-4 h-1 rounded-full bg-[#222]"><div className="h-full bg-[#FF6B00]" style={{width:`${course.progress}%`}}/></div><p className="text-xs text-[#777] mt-2">{course.progress}% concluído</p><div className="mt-7 border-t border-[#262626] pt-6"><h2 className="font-bold text-lg">Sobre este conteúdo</h2><p className="text-sm leading-6 text-[#888] mt-3">{course.desc}</p></div></div></section><aside className="rounded-2xl border border-[#262626] bg-[#151515] overflow-hidden h-fit"><div className="p-5 border-b border-[#262626]"><p className="text-[10px] uppercase tracking-[.18em] text-[#666]">Conteúdo</p><h2 className="font-bold mt-1">Módulos e aulas</h2></div><div>{lessons.map((item,i)=><button key={item} onClick={()=>setLesson(i)} className={`w-full text-left flex items-center gap-3 p-4 border-b border-[#222] ${lesson===i?'bg-[#FF6B0014]':''}`}><span className={`h-8 w-8 rounded-full grid place-items-center shrink-0 ${lesson===i?'bg-[#FF6B00]':'bg-[#222]'}`}>{i<lesson?<CheckCircle2 size={15}/>:i>lesson?<Lock size={14}/>:<Play size={14} fill="currentColor"/>}</span><span><span className="block text-sm font-semibold">{item}</span><span className="block text-[10px] text-[#666] mt-1">Aula {i+1} · 08 min</span></span></button>)}</div></aside></div></main></div>
}
