'use client'

import { useEffect, useState } from 'react'
import { Save, LogOut } from 'lucide-react'

type Course={id:string;tag:string;title:string;desc:string;thumb:string;progress:number;number:string}
const defaults:Course[]=[
{id:'codigo',tag:'CÓDIGO',title:'Código da Disciplina',desc:'Sistema integrado de transformação humana aplicado à vida real.',thumb:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85',progress:75,number:'70'},
{id:'sabotadores',tag:'MENTALIDADE',title:'7 Sabotadores da Disciplina',desc:'Identifique os padrões que sabotam sua execução.',thumb:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=85',progress:50,number:'7'},
{id:'personal',tag:'NEGÓCIOS',title:'Personal Empresário',desc:'Transforme conhecimento, serviço e disciplina em negócio.',thumb:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85',progress:100,number:'12'},
{id:'desafio70',tag:'DESAFIO',title:'Desafio 70 Dias',desc:'Um ciclo de execução para construir consistência.',thumb:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=85',progress:30,number:'70'},
{id:'pos',tag:'ESTUDO',title:'Pós-Graduação III',desc:'Conteúdos de estudo, repertório e aplicação prática.',thumb:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=85',progress:40,number:'10'},
{id:'mentoria',tag:'AO VIVO',title:'Mentoria',desc:'Direcionamentos para transformar intenção em execução.',thumb:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85',progress:20,number:'19'}]
export default function Adm(){
 const [logged,setLogged]=useState(false),[user,setUser]=useState(''),[pass,setPass]=useState(''),[items,setItems]=useState(defaults)
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('hope_content_v2')||'[]');if(Array.isArray(s)&&s.length)setItems(defaults.map(d=>({...d,...s.find((x:Course)=>x.id===d.id)})))}catch{}},[])
 const save=()=>localStorage.setItem('hope_content_v2',JSON.stringify(items))
 if(!logged)return <main className="min-h-screen bg-[#0A0A0A] text-white flex items-center justify-center px-4"><section className="w-full max-w-[360px] rounded-2xl border border-[#262626] bg-[#151515] p-6"><div className="text-center text-3xl font-extrabold text-[#FF6B00] mb-7">HOPE+</div><h1 className="text-lg font-bold">Área administrativa</h1><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Usuário" className="mt-5 w-full h-11 rounded-xl bg-[#0A0A0A] border border-[#262626] px-4 outline-none"/><input value={pass} onChange={e=>setPass(e.target.value)} type="password" placeholder="Senha" className="mt-3 w-full h-11 rounded-xl bg-[#0A0A0A] border border-[#262626] px-4 outline-none"/><button onClick={()=>user==='admin'&&pass==='admin123'&&setLogged(true)} className="mt-4 w-full h-11 rounded-xl bg-[#FF6B00] font-extrabold">ENTRAR</button><p className="text-xs text-[#777] mt-5 text-center">Se esquecer login: <b className="text-white">admin / admin123</b></p></section></main>
 return <main className="min-h-screen bg-[#0A0A0A] text-white p-4 md:p-8"><div className="max-w-6xl mx-auto"><header className="flex items-center justify-between border-b border-[#262626] pb-5"><div><div className="text-2xl font-extrabold text-[#FF6B00]">HOPE+</div><p className="text-xs text-[#666] mt-1">Painel administrativo</p></div><button onClick={()=>setLogged(false)} className="inline-flex items-center gap-2 text-xs text-[#888]"><LogOut size={16}/>Sair</button></header><div className="flex items-center justify-between mt-7 mb-5"><div><h1 className="text-xl font-extrabold">Cursos</h1><p className="text-xs text-[#666] mt-1">Edite e salve o conteúdo da área de membros.</p></div><button onClick={save} className="inline-flex items-center gap-2 rounded-full bg-[#FF6B00] px-4 py-2 text-xs font-bold"><Save size={14}/>SALVAR ALTERAÇÕES</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-5">{items.map((c,i)=><section key={c.id} className="rounded-2xl border border-[#262626] bg-[#151515] p-5"><div className="flex gap-4"><div className="w-28 h-20 shrink-0 rounded-xl bg-cover bg-center" style={{backgroundImage:`url(${c.thumb})`}}/><div className="min-w-0"><span className="text-[10px] font-bold text-[#FF6B00]">{c.tag}</span><h2 className="font-bold mt-1">{c.title}</h2></div></div><label className="block text-[10px] uppercase text-[#666] mt-5">Título</label><input value={c.title} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,title:e.target.value}:x))} className="mt-1 w-full h-10 rounded-lg bg-[#0A0A0A] border border-[#262626] px-3 text-sm outline-none"/><label className="block text-[10px] uppercase text-[#666] mt-4">Progresso (%)</label><input type="number" min="0" max="100" value={c.progress} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,progress:Math.max(0,Math.min(100,Number(e.target.value)))}:x))} className="mt-1 w-full h-10 rounded-lg bg-[#0A0A0A] border border-[#262626] px-3 text-sm outline-none"/><label className="block text-[10px] uppercase text-[#666] mt-4">Thumbnail URL</label><input value={c.thumb} onChange={e=>setItems(v=>v.map((x,j)=>j===i?{...x,thumb:e.target.value}:x))} className="mt-1 w-full h-10 rounded-lg bg-[#0A0A0A] border border-[#262626] px-3 text-xs outline-none"/></section>)}</div></div></main>
}
