'use client'
import Link from 'next/link'
import {BookOpen,CalendarDays,ChevronRight,Home,Library,Medal,Target,UserRound,Users,Zap} from 'lucide-react'

export const nav=[
 ['Início','/aluno',Home],['Cursos','/aluno/cursos',BookOpen],['Minha jornada','/aluno/jornada',Target],['Desafios','/aluno/desafios',CalendarDays],['Comunidade','/aluno/comunidade',Users],['Conquistas','/aluno/conquistas',Medal],['Certificados','/aluno/certificados',Medal],['Biblioteca','/aluno/biblioteca',Library],['Perfil','/aluno/perfil',UserRound]
] as const

export const courses=[
 {id:'codigo',tag:'CÓDIGO',title:'Código da Disciplina',desc:'Os 10 pilares para transformar disciplina em comportamento aplicado.',progress:75,number:'10 pilares',thumb:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=85'},
 {id:'sabotadores',tag:'MENTALIDADE',title:'7 Sabotadores da Disciplina',desc:'Identifique os padrões que destroem sua execução antes que destruam seus resultados.',progress:50,number:'7 aulas',thumb:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85'},
 {id:'personal',tag:'NEGÓCIOS',title:'Personal Empresário',desc:'Conhecimento, serviço e disciplina transformados em negócio.',progress:100,number:'12 aulas',thumb:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85'},
 {id:'desafio70',tag:'DESAFIO',title:'Desafio 70 Dias',desc:'Um ciclo de execução para construir consistência invisível.',progress:30,number:'70 dias',thumb:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=85'},
 {id:'pos',tag:'ESTUDO',title:'Pós-Graduação III',desc:'Estudo, repertório e aplicação prática para ampliar sua capacidade.',progress:40,number:'10 módulos',thumb:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=85'},
 {id:'mentoria',tag:'AO VIVO',title:'Mentoria',desc:'Direcionamento para transformar intenção em execução.',progress:20,number:'19 encontros',thumb:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1600&q=85'}
]

export function MemberShell({active,children,title='Área de membros'}:{active:string;children:React.ReactNode;title?:string}){
 return <div className="min-h-screen bg-[#090909] text-white selection:bg-[#FF6B00] selection:text-white">
  <aside className="fixed inset-y-0 left-0 z-50 hidden w-[258px] border-r border-white/[.07] bg-[#0d0d0d] lg:flex lg:flex-col">
   <div className="flex h-20 items-center border-b border-white/[.06] px-7"><Link href="/aluno" className="text-[28px] font-black tracking-[-.06em]">HOPE<span className="text-[#FF6B00]">+</span></Link></div>
   <div className="px-5 pt-6"><div className="rounded-2xl border border-[#FF6B00]/20 bg-gradient-to-br from-[#FF6B00]/10 to-transparent p-4"><p className="text-[9px] font-bold uppercase tracking-[.2em] text-[#777]">Seu momento</p><div className="mt-2 flex items-center justify-between"><b className="text-xl">NÍVEL 07</b><span className="text-[10px] font-black text-[#FF6B00]">DISCIPLINADO</span></div><div className="mt-3 h-1.5 rounded-full bg-white/[.06]"><div className="h-full w-[68%] rounded-full bg-[#FF6B00]"/></div><p className="mt-2 text-[9px] text-[#666]">680 / 1.000 XP para o próximo nível</p></div></div>
   <nav className="mt-6 flex-1 space-y-1 px-3">{nav.map(([label,href,Icon])=><Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-[12px] font-semibold transition ${active===href?'bg-[#FF6B00]/10 text-[#FF6B00]':'text-[#777] hover:bg-white/[.035] hover:text-white'}`}><Icon size={16}/><span>{label}</span>{active===href&&<span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#FF6B00]"/>}</Link>)}</nav>
   <div className="border-t border-white/[.06] p-4"><Link href="/adm" className="flex items-center justify-between rounded-xl bg-white/[.025] px-4 py-3 text-[10px] font-bold text-[#555] hover:text-white"><span>GESTÃO HOPE+</span><ChevronRight size={14}/></Link></div>
  </aside>
  <main className="min-h-screen lg:ml-[258px]">
   <header className="sticky top-0 z-40 border-b border-white/[.06] bg-[#090909]/90 px-4 py-3 backdrop-blur-xl sm:px-6 lg:px-10"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="truncate text-[8px] font-bold uppercase tracking-[.22em] text-[#555]">HOPE+ / {title}</p><p className="mt-1 text-xs font-semibold text-white/90">Mentalidade • Ação • Resultado</p></div><div className="flex items-center gap-2"><div className="hidden rounded-xl border border-white/[.07] bg-white/[.025] px-3 py-2 text-[10px] text-[#777] sm:block">🔥 12 dias</div><Link href="/aluno/perfil" className="grid h-9 w-9 place-items-center rounded-full border border-[#FF6B00]/30 bg-[#FF6B00]/10 text-xs font-black text-[#FF6B00]">L</Link></div></div></header>
   {children}
  </main>
  <nav className="fixed bottom-0 left-0 right-0 z-50 grid h-[70px] grid-cols-5 border-t border-white/[.08] bg-[#0d0d0d]/95 pb-[env(safe-area-inset-bottom)] backdrop-blur-xl lg:hidden">{[['Início','/aluno',Home],['Cursos','/aluno/cursos',BookOpen],['Desafios','/aluno/desafios',Target],['Comunidade','/aluno/comunidade',Users],['Perfil','/aluno/perfil',UserRound]].map(([label,href,Icon])=><Link key={label as string} href={href as string} className={`flex flex-col items-center justify-center gap-1 text-[9px] font-bold ${(active===href)?'text-[#FF6B00]':'text-[#666]'}`}><Icon size={18}/>{label}</Link>)}</nav>
 </div>
}

export function CourseCard({course}:{course:any}){return <Link href={`/aluno/${course.id}`} className="group overflow-hidden rounded-[20px] border border-white/[.07] bg-[#131313] shadow-[0_12px_40px_rgba(0,0,0,.18)] transition duration-300 hover:-translate-y-1 hover:border-[#FF6B00]/40"><div className="relative aspect-[16/9] overflow-hidden"><img src={course.thumb} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/15 to-transparent"/><span className="absolute left-4 top-4 rounded-md bg-[#FF6B00] px-2.5 py-1.5 text-[9px] font-black tracking-wide">{course.tag}</span><span className="absolute bottom-4 right-4 rounded-full border border-white/10 bg-black/60 px-3 py-1.5 text-[9px] text-white/80">{course.number}</span></div><div className="p-5"><h3 className="text-[15px] font-black tracking-tight">{course.title}</h3><p className="mt-2 min-h-[38px] text-[11px] leading-5 text-[#777]">{course.desc}</p><div className="mt-5 flex items-center justify-between"><span className="text-[9px] font-bold uppercase tracking-widest text-[#555]">{course.progress===100?'CONCLUÍDO':'EM ANDAMENTO'}</span><b className="text-[11px] text-[#FF6B00]">{course.progress}%</b></div><div className="mt-2 h-1 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#FF6B00]" style={{width:`${course.progress}%`}}/></div><div className="mt-4 flex items-center justify-between text-[9px] font-black"><span className="text-[#555]">CONTINUAR JORNADA</span><span className="grid h-7 w-7 place-items-center rounded-full bg-[#FF6B00] text-white"><ChevronRight size={13}/></span></div></div></Link>}
