'use client'
import Link from 'next/link'
import {ArrowRight,Award,CheckCircle2,Flame,Play,Target,Trophy,TrendingUp,Zap} from 'lucide-react'
import {CourseCard,MemberShell,courses} from './components'

export default function Aluno(){return <MemberShell active="/aluno">
 <div className="mx-auto max-w-[1500px] px-4 pb-28 pt-6 sm:px-6 lg:px-10 lg:pb-12 lg:pt-9">
  <section className="relative overflow-hidden rounded-[28px] border border-white/[.08] bg-[#111] shadow-[0_25px_80px_rgba(0,0,0,.3)]">
   <img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2000&q=85" alt="" className="absolute inset-0 h-full w-full object-cover opacity-30"/>
   <div className="absolute inset-0 bg-gradient-to-r from-[#080808] via-[#080808]/90 to-[#080808]/20"/>
   <div className="relative grid min-h-[330px] items-end gap-8 p-6 sm:p-9 lg:grid-cols-[1fr_320px] lg:p-12">
    <div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-[#FF6B00]/30 bg-[#FF6B00]/10 px-3 py-1.5 text-[9px] font-black uppercase tracking-[.18em] text-[#FF6B00]"><span className="h-1.5 w-1.5 rounded-full bg-[#FF6B00]"/> Jornada ativa</span><p className="mt-6 text-[10px] font-bold uppercase tracking-[.25em] text-white/40">BEM-VINDO DE VOLTA</p><h1 className="mt-2 text-4xl font-black leading-[.95] tracking-[-.045em] sm:text-5xl lg:text-6xl">Olá, Lucas.<br/><span className="text-[#FF6B00]">Vamos executar.</span></h1><p className="mt-5 max-w-xl text-xs leading-6 text-white/55 sm:text-sm">Disciplina não é intenção. É aquilo que você executa quando ninguém está olhando.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/aluno/codigo" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#FF6B00] px-6 py-3.5 text-[10px] font-black shadow-[0_8px_30px_rgba(255,107,0,.2)]">CONTINUAR TREINAMENTO <Play size={13} fill="white"/></Link><Link href="/aluno/jornada" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-6 py-3.5 text-[10px] font-black text-white/80">VER MINHA JORNADA <ArrowRight size={13}/></Link></div></div>
    <div className="rounded-2xl border border-white/10 bg-black/40 p-5 backdrop-blur-md"><div className="flex items-center justify-between"><span className="text-[9px] font-bold uppercase tracking-[.2em] text-white/40">Próximo nível</span><span className="text-[10px] font-black text-[#FF6B00]">68%</span></div><div className="mt-3 h-2 rounded-full bg-white/[.08]"><div className="h-full w-[68%] rounded-full bg-[#FF6B00]"/></div><div className="mt-4 flex items-end justify-between"><div><b className="text-3xl font-black">07</b><p className="text-[9px] text-white/35">DISCIPLINADO</p></div><div className="text-right"><b className="text-lg">1.240</b><p className="text-[9px] text-white/35">XP TOTAL</p></div></div></div>
   </div>
  </section>

  <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-4">{[[Flame,'12','STREAK','dias consecutivos'],[Zap,'1.240','XP','+120 esta semana'],[TrendingUp,'07','NÍVEL','Disciplinado'],[CheckCircle2,'3/6','CURSOS','50% da jornada']].map(([I,v,l,s])=><div key={l as string} className="rounded-2xl border border-white/[.07] bg-[#131313] p-4 sm:p-5"><div className="flex items-start justify-between"><div><b className="text-2xl font-black sm:text-3xl">{v}</b><p className="mt-1 text-[8px] font-black uppercase tracking-[.16em] text-[#555]">{l}</p></div><I size={17} className="text-[#FF6B00]"/></div><p className="mt-3 text-[9px] text-[#555]">{s}</p></div>)}</section>

  <section className="mt-10"><div className="mb-5 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#555]">Seu treinamento</p><h2 className="mt-1 text-2xl font-black tracking-tight">Continue de onde parou</h2></div><Link href="/aluno/cursos" className="inline-flex items-center gap-1 text-[10px] font-black text-[#FF6B00]">VER TODOS <ArrowRight size={13}/></Link></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{courses.slice(0,3).map(c=><CourseCard key={c.id} course={c}/>)}</div></section>

  <section className="mt-10 grid gap-5 xl:grid-cols-[1.45fr_.85fr]">
   <Link href="/aluno/desafios" className="group relative min-h-[250px] overflow-hidden rounded-[22px] border border-white/[.07] bg-[#131313] p-6 sm:p-8"><div className="absolute right-0 top-0 h-full w-2/3 bg-gradient-to-l from-[#FF6B00]/10 to-transparent"/><div className="relative flex h-full flex-col justify-between"><div><span className="rounded-md bg-[#FF6B00] px-2.5 py-1.5 text-[9px] font-black">DESAFIO ATIVO</span><h2 className="mt-5 text-3xl font-black tracking-tight">70 DIAS</h2><p className="mt-1 max-w-md text-xs leading-5 text-[#666]">Um ciclo de execução para construir consistência invisível e fortalecer sua identidade.</p></div><div><div className="flex justify-between text-[9px] font-bold"><span className="text-[#555]">DIA 37 / 70</span><span>53%</span></div><div className="mt-2 h-2 max-w-xl rounded-full bg-white/[.06]"><div className="h-full w-[53%] rounded-full bg-[#FF6B00]"/></div><div className="mt-5 inline-flex items-center gap-2 text-[9px] font-black text-[#FF6B00]">CONTINUAR DESAFIO <ArrowRight size={13}/></div></div></div></Link>
   <Link href="/aluno/conquistas" className="rounded-[22px] border border-white/[.07] bg-[#131313] p-6 sm:p-8"><div className="flex items-center justify-between"><div className="rounded-xl bg-[#FF6B00]/10 p-3 text-[#FF6B00]"><Award size={20}/></div><span className="text-[9px] font-black text-[#555]">72%</span></div><p className="mt-6 text-[9px] font-black uppercase tracking-[.2em] text-[#555]">Próxima conquista</p><h3 className="mt-2 text-xl font-black">Consistência Invisível</h3><p className="mt-2 text-xs leading-5 text-[#666]">Complete mais 3 dias consecutivos para desbloquear este marco.</p><div className="mt-5 h-1.5 rounded-full bg-white/[.06]"><div className="h-full w-[72%] rounded-full bg-[#FF6B00]"/></div></Link>
  </section>

  <section className="mt-10"><div className="mb-5"><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#555]">Recomendado para você</p><h2 className="mt-1 text-2xl font-black">Expanda seu campo</h2></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{courses.slice(3).map(c=><CourseCard key={c.id} course={c}/>)}</div></section>

  <section className="mt-10 rounded-[22px] border border-[#FF6B00]/15 bg-gradient-to-r from-[#FF6B00]/[.08] to-transparent p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#FF6B00]">Comando do dia</p><h2 className="mt-2 text-xl font-black">Reduza a missão. Execute o mínimo. Zero não conta.</h2><p className="mt-2 max-w-2xl text-xs text-[#777]">Escolha uma ação de 10 minutos e registre sua execução.</p></div><Link href="/aluno/desafios" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[#FF6B00] px-5 py-3 text-[10px] font-black">EXECUTAR AGORA <ArrowRight size={13}/></Link></div></section>
 </div>
 </MemberShell>}
